# https://travis-ci.org/#!/phlax/tpls

dist: bionic
language: python
env:
  global:
    - PYTHONUNBUFFERED=1

install:
  - make deb
  - make pysh
  - pip install pyyaml

script:
  - ls dist
  - export COMPOSE_FILE=./example/docker-compose.yml

  - pysh ./tests/templates
  - pysh ./tests/commit

  - shellcheck -x usr/lib/tpls/*
  - shellcheck -x usr/bin/*
