version: $TPL_COMPOSE_VERSION

services:
  $TPL_SERVICE:
    image: $TPL_IMAGE
    restart: $TPL_RESTART
    networks:
      $TPL_NETWORK:
        ipv4_address: $TPL_IP
    expose:
      - "80"
      - "443"
    volumes:
      - $TPL_CONFIG:/etc/nginx/conf.d
      - $TPL_ASSETS:$TPL_ASSETS_MOUNT
    labels:
      custom_label: $TPL_LABEL
    healthcheck:
      interval: 10s
      retries: 20
      test: $TPL_HEALTHCHECK_COMMAND
